TheThingsNetwork/lorawan-devices

- README.md
- vendor/example/windsensor-codec.yaml
- vendor/example/windsensor-profile.yaml
People are likely to copy-paste the example vendor and change the fields accordingly.
To support them in this process, I've added the descriptions in the codec and profile files
- Added descriptions in the example codec and profile
> Small changes to clarify the example

- README.md
- vendor/example/windsensor-profile.yaml
Quickfix - updated link for partner to find their LoRa Alliance ID.
- Updated URL
> doc: Updated vendorProfileID link

- vendor/example/windsensor.yaml
Add:
- resellerURL
- video
Only applicable after merging the below PR
https://github.com/lorawan-schema/draft-devices/pull/7
Added the fields:
- resellerURL
- video
> Update example file

- vendor/decentlab/dl-iam.yaml
Set DL-IAM datasheet URL to a static location. Otherwise, the current URL is a dynamically generated and may be removed any time.
- vendor/decentlab/dl-iam.yaml: changed dataSheetURL field.
> dl-iam: set datasheet url to static location

- vendor/the-things-products/the-things-uno.yaml
Add fields to The Things Uno for testing @mjamescompton
> Add video and reseller to The Things Uno

- vendor/aquascope/bvs.yaml
- vendor/aquascope/wwd.yaml
- vendor/example/windsensor.yaml
- vendor/imst/ioke868.yaml
- vendor/imst/range-extender.yaml
- vendor/stmicroelectronics/nucleo-wl55jc1.yaml
- vendor/stmicroelectronics/nucleo-wl55jc2.yaml
- vendor/the-things-products/the-things-uno.yaml
According to the schema, the `video` device field is wrong.
> Correct device video field according to schema

- vendor/digital-matter/oyster.js
- vendor/digital-matter/yabby-edge.js
Added more rounding of battery voltages
- ...
- ...
> More rounding in Oyster and Yabby Edge uplink decoders

- README.md
Add a note that filenames should be lowercase, and link to instructional video.
> Add video and lowercase filename note

- README.md
Move the contributing section up so that everyone reads the instructions to `make validate fmt`
> Move contributing up in the README

- vendor/iotsens/airquality-device.yaml
- vendor/iotsens/lidar-device.yaml
- vendor/iotsens/sound-device.yaml
> Update IoTsens devices

- vendor/beiselen/radar.yaml
Updated sensor(`DigiSilo Radar`) information as per vendor.
1. Modified
- description
- photos resolution
2. Added
- sensors
- dimensions
- weight
- battery
- operatingConditions
- ipCode
- photos
> Update DigiSilo Radar Sensor

- vendor/bosch/tps110.yaml
Updated `tps110` information as per vendor.
Added `radar` to sensors.
> Update Bosch TPS110

- vendor/multi-tech/multi-tech-xdot.yaml
Modified firmware version for multi-tech xDot
- Modified firmware version from `1.0` to `3.5.5`.
> Modify firmware version for multi-tech xDot

- vendor/moko/lw001-bg.yaml
- vendor/moko/lw003-b.yaml
- vendor/moko/lw004.yaml
- vendor/moko/lw005-mp.yaml
Modified name & description for the `MOKO` devices as per Vendor.
> Modify name & description of Moko devices

- vendor/index.yaml
Add SenseCAP to vendor index. Missing from https://github.com/TheThingsNetwork/lorawan-devices/pull/85/files
> Add SenseCAP to vendor index

- bin/validate.js
- vendor/the-things-industries/generic-node-sensor-edition-codec.yaml
- vendor/the-things-industries/generic-node-sensor-edition.yaml
Closes #120 
- Check that the codec file exists
- Check that file names are lowercase, references #108
> Check codec file existence

- README.md
- vendor/example/windsensor.yaml
Explain new fields added in LoRaWAN Schema, ref: https://github.com/lorawan-schema/draft-devices/pull/15
Fields added in LoRaWAN schema:
- manufacturerSuggestedRetailPrice
- firmwareConfigurability
Updated fields:
- keyProvisioning
- sensors
Fields added to make the device repo more complete.
> Describe new fields of LoRaWAN schema

- lib/draft/schema.json
- vendor/example/windsensor.yaml
Closes https://github.com/TheThingsNetwork/lorawan-devices/issues/75
- Add new section `bridgeInterfaces` for things like M-Bus, Modbus, RS-485 etc
- Extended examples
> Add `bridgeInterfaces` and extended examples

- .github/workflows/release.yml
- website/Makefile
- website/webpack.config.js
This make the BASE_URL and BASE_PATH configurable during deployment. Also allows for custom configuration locally via `.envrc`
- Update release and webpack to use env variables
> Add BASE_URL and BASE_PATH env variables to website

- website/layouts/devices/list.html
- website/layouts/partials/head.html
The devices/ view is exactly the same as the root, so the page should redirect to the root, this now recognises the base_path env variable.
I also noticed it was not displaying the images correctly so I fix that incase this page is ever seen.
- Fix meta redirect in head.html
- Fix device-list.html attribute in devices/list.html
...
- ...
> Fix device view and redirect on view

- website/layouts/_default/baseof.html
- website/package.json
- website/src/js/index.js
- website/src/styles/global.styl
- website/src/styles/index.styl
- website/yarn.lock
Closes #160
- Change to S3 bucket url
The required `ttui-1.0.0-alpha.1.tar.gz`file does not exist in the bucket yet, waiting on this to be merged https://github.com/TheThingsIndustries/design/pull/17
We can also close this PR https://github.com/TheThingsNetwork/lorawan-devices/pull/161
> Update @tti/design dependencies url

- website/layouts/partials/header.html
- website/src/styles/global.styl
Header was defaulting to localhost
- Add rootUrl prop to `ttn-header` component
> Add rootUrl prop to header component

- website/layouts/devices/list.html
The device list where not filtering based on the page
- Reverted a previous mistake,  pass the page variables to `device-list.html`
> Fix filtered device lists

- website/tools/build/pkg/hugo/hugo.go
Remove vendors with no devices.
> website: Remove vendors without devices

- website/layouts/partials/head.html
Fix missing `/` in og image url
> Fix og-image-url

- website/package.json
- website/yarn.lock
Update to latest version of design repository to fix some issues with the header component
- Changed a 2 to 3
> Update design repository to ttui-1.0.0-alpha.3

- .github/workflows/release.yml
- website/layouts/partials/header.html
Set base url to www.thethingsnetwork.org
- Update base url
- Update header url
> Set base url to www.thethingsnetwork.org

- website/config/_default/config.toml
Fix redirect on /devices to root
- Update config baseURL
> Update baseurl in config

- website/layouts/index.html
- website/package.json
- website/yarn.lock
- Update to latest ttui
- Update page title
> Update to the ttui-1.0.0-alpha.7 and fix root title

- vendor/elsys/elsys-as923-profile.yaml
- vendor/elsys/elsys-au915-profile.yaml
- vendor/elsys/elsys-eu868-profile.yaml
- vendor/elsys/elsys-us902-profile.yaml
- vendor/elsys/elt-2-codec.yaml
- vendor/elsys/elt-2.yaml
- vendor/elsys/elt-lite-codec.yaml
- vendor/elsys/elt-lite.yaml
- vendor/elsys/elt-ultrasonic-codec.yaml
- vendor/elsys/elt-ultrasonic.yaml
- vendor/elsys/ems-codec.yaml
- vendor/elsys/ems-desk-codec.yaml
- vendor/elsys/ems-desk.yaml
- vendor/elsys/ems-door-codec.yaml
- vendor/elsys/ems-door.yaml
- vendor/elsys/ems-lite-codec.yaml
- vendor/elsys/ems-lite.yaml
- vendor/elsys/ems.yaml
- vendor/elsys/ers-co2-codec.yaml
- vendor/elsys/ers-co2-lite-codec.yaml
- vendor/elsys/ers-codec.yaml
- vendor/elsys/ers-eye-codec.yaml
- vendor/elsys/ers-lite-codec.yaml
- vendor/elsys/ers-sound-codec.yaml
- vendor/elsys/ers-sound.yaml
- vendor/elsys/ers-voc-codec.yaml
- vendor/elsys/ers-voc.yaml
- vendor/index.yaml
Add Elsys on index file, remove vendor ID from files 
- index
- yaml files
...
- ...
> Elsys modifications

- README.md
Add a recommendation for decoders files to contain the units they use. Reference  #237 
- Add a recommendation on `README` `Payload Codecs`
> Units Recommendation

- vendor/elsys/ers-co2-lite.yaml
- vendor/elsys/ers-eye.yaml
- vendor/elsys/ers-lite.yaml
- vendor/elsys/ers.yaml
Elsys devices files try to connect to example profile, this is fixed in 4 devices. https://www.thethingsnetwork.org/forum/t/register-end-device-keeps-fetching-forever/49592 
- commented vendorID line
- ers co2 lite, ers eye, ers lite and ers files fixed.
...
- ...
> Elsys fixed files

- vendor/imst/ioke868-codec.yaml
- vendor/imst/ioke868.js
- vendor/imst/ioke868.yaml
- vendor/imst/range-extender-codec.yaml
- vendor/imst/range-extender.js
- vendor/imst/range-extender.yaml
IMST codec update
- ioke868 update
- range extender update
...
- ...
> IMST codec update

- bin/validate.js
- vendor/elsys/ers-co2.yaml
- vendor/tektelic/t00056xx-470-profile.yaml
- vendor/tektelic/t000589x-915-profile.yaml
- vendor/tektelic/t00061xx-470-profile.yaml
- vendor/tektelic/t000662x-915-profile.yaml
Fix profile validation
The profiles weren't validated correctly. This PR fixes that.
This PR also contains fixes for Elsys and Tektelic devices who were invalid but were not caught by CI before.
@Jaime-Trinidad please check with Tektelic if the changes are correct.
> Fix profile validation

- vendor/keller/adt1-tube.yaml
Remove duplicate photo from device.
> Fix duplicate photo in Keller ADT1 Tube

- vendor/izinto/izi-io-4840-grid.yaml
- vendor/izinto/izi-io-4840-heat.yaml
Changed description text and product URL for two products.
...
- ...
- ...
...
- ...
> minor corrections

- website/layouts/devices/single.html
- website/layouts/partials/device-list.html
- website/package.json
- website/src/styles/global.styl
- website/src/styles/layouts/devices/single.styl
- website/src/styles/layouts/partials/device-list.styl
- website/yarn.lock
Add a contact form to single device page 
- Add form
- Update ttui version
- Update button classes
> Add contact form

- vendor/ellenex/pls2-l.yaml
Corrected device name for PLS2-L
- ...
- ...
...
- ...
> Corrected device name for PLS2-L

- lib/draft/package-lock.json
- lib/draft/schema.json
References https://github.com/TheThingsNetwork/lorawan-stack/issues/3513
- Update the `lib/draft` dependencies
- Add CN470-510 and AS923 variants used in newer RP versions
> Add additional band regions

- website/layouts/partials/header.html
- website/package.json
- website/src/js/index.js
- website/yarn.lock
Update to ttui-1.0.0-alpha.14 and add new ttn-header
- Update to ttui-1.0.0-alpha.14 
- Include ttui header
> Update to ttui-1.0.0-alpha.14 and add new ttn-header

- README.md
- website/README.md
- website/config/_default/config.toml
- website/content/_index.md
- website/layouts/index.html
Remove LoRaWAN name due to trademark issues
Ask @wienke for context
> Remove LoRaWAN from titles

- website/yarn.lock
Update all out of date dependancies.
- Run `yarn upgrade`
After this task I will check all the dependancy bot pr's and close them.
- ...
> Run yarn upgrade to update all website dependencies

- website/layouts/index.html
- website/package.json
- website/yarn.lock
#372 
- Update homepage title
- Update to latest design repo to import new footer logos
> Apply LoRaWAN brand guidelines

- website/layouts/devices/single.html
- website/package.json
- website/yarn.lock
Update design repo to version 1.0.0-alpha.18
> Update design repo to version 1.0.0-alpha.18

- vendor/iothings/iotracker3.js
Fixes in ioTracker 3 uplink decoder
- Fix in GPS uplink parser.
- TTN codestyle and notation alignment fixes.
> Fixes in ioTracker 3 uplink decoder

- vendor/plenom/busylight.yaml
The Name of the Device was not correct.
...
- Changed name of device
...
- ...
> Corrected Busylight Device Name

- vendor/strega/motorized-valve-profile-865.yaml
- vendor/strega/motorized-valve-profile-868.yaml
- vendor/strega/motorized-valve-profile-915.yaml
- vendor/strega/motorized-valve.yaml
- vendor/strega/smart-emitter-profile-865.yaml
- vendor/strega/smart-emitter-profile-868.yaml
- vendor/strega/smart-emitter-profile-915.yaml
- vendor/strega/smart-emitter-profile-923.yaml
- vendor/strega/smart-emitter.yaml
- vendor/strega/smart-switch-profile-865.yaml
- vendor/strega/smart-switch-profile-868.yaml
- vendor/strega/smart-switch-profile-915.yaml
- vendor/strega/smart-switch-profile-923.yaml
- vendor/strega/smart-switch.yaml
- vendor/strega/smart-valve-profile-865.yaml
- vendor/strega/smart-valve-profile-868.yaml
- vendor/strega/smart-valve-profile-915.yaml
- vendor/strega/smart-valve-profile-923.yaml
- vendor/strega/smart-valve.yaml
Added IN865 frequency profile to all the Strega devices and updated the End Device `yaml` file with the IN865 profile.
- Added IN865 frequency profile.
- Updated the End Device `yaml` file.
...
...
> Add IN865 profile for Strega Devices

- vendor/strega/motorized-valve-profile-865.yaml
- vendor/strega/smart-emitter-profile-865.yaml
- vendor/strega/smart-switch-profile-865.yaml
- vendor/strega/smart-valve-profile-865.yaml
Update regional parameters version in the Strega devices IN865 frequency profile.
- Regional Parameters Version in IN865 profile to `RP001-1.0.2-RevB`.
...
...
> Update IN865 profile regional parameters version in Strega devices

- vendor/nke-watteco/intenso-sensor.js
> Update label of the decoding

- vendor/laird/rs1xx-ext-multi-sensor-codec.yaml
- vendor/laird/rs1xx-ext-multi-sensor.js
- vendor/laird/rs1xx-ext-temp-1w-sensor-codec.yaml
- vendor/laird/rs1xx-ext-temp-1w-sensor.js
- vendor/laird/rs1xx-ext-temp-rtd-sensor-codec.yaml
- vendor/laird/rs1xx-ext-temp-rtd-sensor.js
- vendor/laird/rs1xx-temp-rh-sensor-codec.yaml
- vendor/laird/rs1xx-temp-rh-sensor.js
Corrects the Laird Connectivity range of RS1xx sensor timestamp epoch
The epoch start year has been corrected from 2000 to 2015
> Correct epoch time

- website/package.json
- website/src/js/index.js
- website/yarn.lock
Update ttui to version 1.0.0-alpha.27 and add new ttn footer
- Update ttui version 
- Include ttui-footer
> Update ttui to version 1.0.0-alpha.27 and add new ttn footer

- website/content/_index.md
Remove text mentioning 2021 conference
> Update website content

- website/package.json
- website/yarn.lock
Update TTUI dependency to the alpha-29 version
> Update ttui dependency to alpha-29

- vendor/sensecap/sensecap210x-codec.yaml
- vendor/sensecap/sensecap210x-common-decoder.js
- vendor/sensecap/sensecaps2100-data-logger.yaml
- vendor/sensecap/sensecaps2101-temp-humid.yaml
- vendor/sensecap/sensecaps2102-light.yaml
- vendor/sensecap/sensecaps2103-co2-temp-humid.yaml
- vendor/sensecap/sensecaps2104-soil-moisture-temp.yaml
- vendor/sensecap/sensecaps2105-soll-moisture-temp-ec.yaml
Hi, we add the SenseCAP S210x decoder.
...
- ...
- ...
...
- ...
> Add: add SenseCAP decoder

- vendor/seeed/loradevelopkit-e5.yaml
- vendor/seeed/loraeminidevboard-e5.yaml
- vendor/sensecap/loramodule-e5.yaml
- vendor/sensecap/sensecap-air-th.yaml
- vendor/sensecap/sensecap-co2.yaml
- vendor/sensecap/sensecap-light.yaml
- vendor/sensecap/sensecap-pressure.yaml
- vendor/sensecap/sensecap-soil-th.yaml
- vendor/sensecap/sensecaps2100-data-logger.yaml
- vendor/sensecap/sensecaps2101-temp-humid.yaml
- vendor/sensecap/sensecaps2102-light.yaml
- vendor/sensecap/sensecaps2103-co2-temp-humid.yaml
- vendor/sensecap/sensecaps2104-soil-moisture-temp.yaml
- vendor/sensecap/sensecaps2105-soll-moisture-temp-ec.yaml
Hi! We need to change our product names and the PR is necessary.
Please help us to change it, Thanks!
...
- ...
- ...
...
- ...
> Update: Change the names of products

- vendor/cotx/cotxpetfon.yaml
Modify cotxpetfon display name
- ...
- ...
...
- ...
> Modify cotxpetfon display name

- vendor/twtg/ds-vb-01-xx.yaml
Fixed typo TWTN->TWTG
- Name of device
Fix to our previous PR, where we added our device.
- ...
> Fixed typo TWTN->TWTG

- .github/workflows/issue-triage.yml
- .github/workflows/release.yml
- .github/workflows/validate.yml
Closes #554 
- Updated actions to versions that use `node 16` and updated handling of `set-output`
> Update to `node 16` and new `set-output `method

- vendor/nwave/ncc405-profile.yaml
- vendor/nwave/nps405-profile.yaml
Update of macVersion for nps405 and ncc405 devices.
> Nwave devices macVersion has been updated

- vendor/gwf/rcm-h200.js
`rcm-h200.js` creates a reference error in the console, the function decodeUplink was fixed to avoid the error #544 
- change function name from `decodeUplinkShort` to `decodeUplink`
- ...
...
- ...
> fix decoder

- website/package.json
- website/yarn.lock
Update ttui to version 1.5.0
- Updated header and buttons styling and content
> Update ttui to version 1.5.0

- website/package.json
- website/yarn.lock
> Update ttui to version 1.6.0

- vendor/the-things-industries/generic-node-sensor-edition-codec.js
Add button in payload formater file from #638 
- ...
- ...
...
- ...
> GNSE button function

- vendor/mutelcor/mtc-aq01.yaml
- vendor/mutelcor/mtc-au01.yaml
- vendor/mutelcor/mtc-cf01.yaml
- vendor/mutelcor/mtc-co2-01.yaml
- vendor/mutelcor/mtc-mh01.yaml
- vendor/mutelcor/mtc-pb01.yaml
Update the Links for Product Infos / Product Datasheets due to the launch of a new website www.mutelcor.com
Also update the Air Quality Sensor as it doesn't support Pressure any more
> Mutelcor LoRaWAN Devices Updates

- website/layouts/devices/single.html
Swap company and device name in contact link
> Swap company and device name in contact link

- vendor/sensative/strips.js
Payload Formatter for Sensative Strips is outdated, they have an updated one on their own [repo,](https://github.com/Sensative/strips-lora-translator-ttn) so its replaced with that one (and it works).
> Update Sensative Strips Payload Formatter

- README.md
Update the README to add instructions for how to get the YAML plugin schema working, since the schema is now hosted.
- Update README
> Update README yaml schema

- vendor/mclimate/vicki-codec.yaml
- vendor/mclimate/vicki.js
- vendor/mclimate/vicki.yaml
- vendor/mclimate/wireless-thermostat.js
- vendor/mclimate/wireless-thermostat.yaml
> Vicki 4.3, WT 1.4

- schema.json
- vendor/example/windsensor.yaml
Add UK to the reseller regions
- Add UK to the reseller regions
...
- ...
> Add UK to the reseller regions

- schema.json
- vendor/yobiiq/index.yaml
This fixes the profile ID validation.
Fix `schema.json`, `additionalProperties` was in the wrong place.
> Fix profile ID validation

- vendor/dragino/lht65.js
- vendor/dragino/lse01.js
- vendor/dragino/lsn50-v2.js
- vendor/dragino/lsn50v2-s31.js
- vendor/milesight-iot/em300-th.js
- vendor/milesight-iot/ws301.js
- vendor/sensative/strips.js
Make normalizers account for undefined fields
- Check all normalizers and make sure that they account for undefined fields.
- Make normalizers account for undefined fields
> Make normalizers account for undefined fields

- vendor/jooby/mtx1.js
Fix data segment processing for Jooby MTX1 device.
- rework JavaScript codec (fix LRC validation, apply latest improvements, replace var with const/let)
...
- ...
> fix data segment processing for Jooby MTX1

- website/package.json
- website/yarn.lock
Collection of dependancy updates 
https://github.com/TheThingsNetwork/lorawan-devices/pull/878
https://github.com/TheThingsNetwork/lorawan-devices/pull/872
https://github.com/TheThingsNetwork/lorawan-devices/pull/872
https://github.com/TheThingsNetwork/lorawan-devices/pull/890
Unable to merge original PRs because of the license/cla
> Update website dependancies

- website/package.json
- website/webpack.config.js
- website/yarn.lock
Upgrade Webpack to v5 to fix build errors.
> Use Webpack v5
