TheThingsNetwork/lorawan-devices

vendor/index.yaml, vendor/the-things-products/the-things-node.yaml
Quickfix PR for an issue that came up while working on https://github.com/TheThingsNetwork/lorawan-stack/issues/3433. Profile IDs for The Things Node do not match with the existing files.
- Rename profile `the-things-node-eu868` to `the-things-node-868`, matching `the-things-node-868.yaml` file.
- Rename profile `the-things-node-us915` to `the-things-node-915`, matching `the-things-node-915.yaml` file.
There should probably be a CI check that will make sure that no such inconsistencies are allowed.
=> Fix Profile IDs for The Things Node to match filenames

vendor/decentlab/dl-dlr2-004.yaml
Add DL-DLR-002 sensor type. 
Add `4-20 ma` sensor in `vendor/decentlab/dl-dlr2-004.yaml` thanks to 78270479.
=> Fix Decentlab DL-DLR-002 sensor type

README.md, vendor/index.yaml
As part of the new device repository website we will be generating partner landing pages. These pages are lacking in company data. 
Here is an example how we could extend the vendor data in the repo. 
An alternative could be to include it here `vendor/index.yaml` but I did not want to over populate this file.
- Add vendor `description`, `vendorURL` and `social` links
Other suggestions included including vendor `location` do you have a good suggestion for a formatted way of including this? 
- Add vendor `description`, `vendorURL` and `social` links to decentlab
=> Extend decentlab vendor fields 

website/config/_default/config.toml, website/content/_index.md
og:site_name = 'The Things Network'
page title = '{{ .Title }} | LoRaWAN Device repository'
The homepage title was repeated.
=> Fix duplicate og title names

README.md, bin/validate.js, vendor/abeeway/abeeway-compact-tracker.yaml, vendor/abeeway/abeeway-geolocation-module.yaml, vendor/abeeway/abeeway-industrial-tracker.yaml, vendor/acrios/acr-cv-101l-m-d.yaml, vendor/heltec/cubecell-solar-sensor-class-a-abp.yaml, vendor/heltec/cubecell-solar-sensor-class-a-otaa.yaml, vendor/heltec/cubecell-solar-sensor-class-c-abp.yaml, vendor/heltec/cubecell-solar-sensor-class-c-otaa.yaml, vendor/mclimate/aqi-sensor.yaml, vendor/mclimate/flood-sensor.yaml, vendor/mclimate/ht-sensor.yaml, vendor/midatronics/sharky-module.yaml, vendor/midatronics/windy-mkr.yaml, vendor/midatronics/windy-module.yaml, vendor/milesight-iot/am107.yaml, vendor/milesight-iot/em300-th.yaml, vendor/milesight-iot/em500-co2.yaml, vendor/milesight-iot/em500-udl.yaml, vendor/moko/lw004.yaml, vendor/nke-watteco/th-sensor.yaml, vendor/sensative/strips.yaml, vendor/strega/smart-emitter.yaml, vendor/strega/smart-switch.yaml, vendor/strega/smart-valve.yaml
Validate hardware versions
References https://github.com/TheThingsIndustries/lorawan-stack-support/issues/455
Example regression that wasn't caught by CI is https://github.com/TheThingsNetwork/lorawan-devices/pull/199/files#diff-ceb33ad2c9c02c0a3bb700d28aa455e801c1b9d7fa8b93620889cff71d92f51cR21-R23 that was fixed by https://github.com/TheThingsNetwork/lorawan-devices/pull/216
cc @jammiemil @Jaime-Trinidad 
- Make sure that when hardware versions are defined for the end device or in firmware versions, that these are consistent
- Fix all validation errors based on the new validation rule
=> Validate hardware versions

vendor/elsys/ers-co2.yaml
Remove `example` vendor ID from Elsys EU 868 profile. Bumped into this while testing.
=> Fix Elsys profile vendor

website/tools/build/pkg/devicerepository/devicerepository.go
The correct field name is `dataSheetURL`. This field does not appear to be used anywhere so far, but good to fix just in case.
cc @mjamescompton
=> Fix Datasheet URL yaml field

vendor/elsys/elsys.js
The ERS-VOC sensor device measures total volatile organic compounds (TVOC) in ppb with a range of 0 to 60000 (https://elsys.se/public/manuals/Operating_Manual_ERS_VOC.pdf page 14).  The official elsys decoder has this data type (https://www.elsys.se/en/elsys-payload/) although it is not (yet) documented in the official sensor payload documentation (https://elsys.se/public/documents/Sensor_payload.pdf).
Add TVOC decoding to the elsys codec.
=> elsys: Add TVOC decoding

vendor/micropelt/mlr003-codec.yaml, vendor/micropelt/mlr003.js
Micropelt MLR003 REV1.1
The Uplink length has increased from 10 bytes to 11 bytes. The Uplink now includes the User Mode and User Value.
- Add decoding for Uplinks of length 11 bytes
- Add examples
The code continues to support decoding of REV1.0 Uplinks, as well as being able to decode REV1.1 Uplinks.
- ...
=> MLR003 REV1.1: Uplink is now 11 bytes

vendor/espeasy/profile-eu868-class-a-abp-101.yaml, vendor/espeasy/profile-eu868-class-a-abp-102.yaml
PR #300 did not fix the RX2 frequency for vendor ESPEasy.
This PR should fix it.
- Change EU868 RX2 freq. for vendor ESPEasy
RX2 settings were discussed [on the forum](https://www.thethingsnetwork.org/forum/t/downlink-on-each-unconfirmed-uplink-abp/58059/23) where it appeared they are still incorrect in the ESPEasy vendor template.
- Correct EU868 RX2 frequency for vendor ESPEasy
=> Fix RX2 frequency 869.525 MHz for vendor ESPEasy

tools/validate-image/main.go, website/tools/build/main.go, website/tools/build/pkg/devicerepository/devicerepository.go, website/tools/build/pkg/hugo/hugo.go
This PR formats the Go files using `gofumpt`. No review required.
=> Fix Go source code formatting

vendor/index.yaml, vendor/keller/adt1-box.yaml, vendor/keller/adt1-tube.yaml
- Adapted to new corporate identity of vendor KELLER
- Changed company name from "_KELLER für Druckmesstechnik AG_" to "_KELLER Druckmesstechnik AG_" rsp. "_KELLER Pressure_"
- Updated URL links to newer versions
- Only superficial changes. Should not break anything.
=> Adapted to new corporate identity of vendor KELLER

vendor/the-things-industries/generic-node-sensor-edition.yaml
Added the `codec: name of codec file` to the End device definition file that was missing, which caused the payload formatter to not show up.
- Added `codec: generic-node-sensor-edition-codec to the End device definition file
=> add codec to definition file

vendor/the-things-industries/generic-node-sensor-edition-868.yaml, vendor/the-things-industries/generic-node-sensor-edition-915.yaml, vendor/the-things-industries/generic-node-sensor-edition-codec.js
This PR updates the GNSE to be marked as LoRaWAN 1.0.3, instead of 1.0.2b, since the underlying LoRaMac-node is actually supporting 1.0.3. The main gain here is that we gain the `CFList` in the US915 band.
- Fix GNSE payload decoder such that temperature calculations round properly.
- Use LoRaWAN 1.0.3 for GNSE.
=> Generic Node description updates

vendor/minol-zenner/edc-communication-module-codec.yaml, vendor/minol-zenner/edc-communication-module-profile.yaml, vendor/minol-zenner/edc-communication-module.js, vendor/minol-zenner/edc-communication-module.yaml, vendor/minol-zenner/index.yaml
this adds the minola-zenner vendor folder and a first version of the edc communications module with a fitting decoder.
- minola-zenner vendor added
- edc communication module profile and decoder added
- make validate ran only when removing "vendor/example" folder temporarily due to a failure in the image checking utility
=> add minol-zenner vendor and edc module definitions

website/layouts/devices/single.html, website/tools/build/pkg/devicerepository/devicerepository.go, website/tools/build/pkg/hugo/hugo.go
The ordering of the devices was based accidentally by weight.
- Set current weight to deviceWeight.
- Set all weight fields to 1.
@Jaime-Trinidad Found while working on the new filters and sorting, more to come soon. The next steps here is for us to use this `weight` field for custom (`featured`)  ordering of device. I'm thinking we make a json object with custom weights for select products. You will then have control over what is featured
- ...
=> Fix device weight set as hugo front matter weight

vendor/plenom/busylight.yaml
modified:   busylight.yaml
Added IN and AS regions
The Busylight device does now support AS923 and IN865-867 regions
- Added AS923 region
- Added IN865-867 region
=> Added IN and AS regions to busylight device

vendor/dragino/lse01.yaml
Make a rollback on 3 `firmware version` on Dragino LS01 device, that were modified on #614 and attends issue #1053 from lorawan-stack-support repo
- `1.1.1` rollback to `1.3`
- `1.2.1` rollback to `lse01 abp 1.1.1`
- `lse01 1.1.4 abp` rollback to `lse01 abp 1.1.4`
New firmware versions should be added, not deleted
- ...
=> Dragino Firmware version

.github/PULL_REQUEST_TEMPLATE.md, bin/validate.js
I noticed with #782 that the validation wasn't catching if `vendorProfileID` existed. I am not sure why, since it can clearly read the value, but replacing it with catching the string does the trick (and I tested it, it works)
Also they tried to change the firmware versions, which gave us a lot of problems not long ago with Dragino, so updating the pull request template too.
- change `if (profile.vendorProfileID)` to `if ('vendorProfileID' in profile)`
- Update pull request template with firmware versions
=> Fix vendorProfileID validation

vendor/gwf/rcm-lrw10.js
Fixes uplink decoder for rcm-lrw10. It did not return a correct structure so we only got "{}" as a result. This fixes it.
Changed formatting of file and return structure.
- update rcm-lrw10.js
can be tested with this payload:
023041438707050300000013BB00000000E039CB
=> fix: Update rcm-lrw10.js to pass correct return structure

vendor/laird/rs1xx-ext-temp-1w-sensor.yaml
Re-enables the Laird RS1xx 1 Wire External Temperature Probe variant.
Uncomments codec YAML references.
Need to check with Johann if time out issues have been resolved.
Re-enabled Laird RS1xx 1 Wire External Temperature Probe variant.
=> Reenable Laird RS1xx 1W Ext Temperature variant

vendor/quandify/cubicmeter-1-1-uplink.js
A mixup in the leak state string has been fixed.
- Medium and Large leak text representation is now matching the leak state
No breaking changes and only affects normalizedUplink
CubicMeter 1.1 Leak string fix
=> Leak state typo fixed

vendor/quandify/cubicmeter-1-1-copper.yaml, vendor/quandify/cubicmeter-1-1-plastic.yaml, vendor/quandify/cubicmeter-1-1-uplink.js
Removed unused functions that were accidentally causing the decoder to crash.
Removed unused functions 
- hexToDecArray
- base64ToDecArray
=> Removed unused functions crashing the decoder

lib/payload.json, vendor/dragino/lsn50-v2-codec.yaml, vendor/dragino/lsn50-v2.js, vendor/dragino/lsn50v2-s31-codec.yaml, vendor/dragino/lsn50v2-s31.js, vendor/milesight-iot/ws301-codec.yaml, vendor/milesight-iot/ws301.js
Change contactState values to lowercase
- Change contactState values to lowercase.
Refs: https://github.com/TheThingsIndustries/lorawan-stack/pull/4450
- Changed the allowed values for `action.contactState` of normalized payloads to lowercase.
=> Change contactState values to lowercase

vendor/mclimate/ht-sensor.js
The sensorTemperature from HT sensors is decoded wrong in the official MClimate codec.
I have sent them an email in march of this year with the proposed correction, but had no response from them.
Basically, with the official codec (as well as the current version in this repo), between the following ranges, the sensorTemperature has an offset of -48°C
- -40°C to -38.5°C
- -14.4°C to -12.9°C
- 11.2°C to 12.7°C
- 36.8°C to 38.3°C
...and so on for a range of 1.5°C every 24°C.
The 4 bytes composing the temperature are now decoded correctly. 
If we take the example byte payload : `010204a1d60400`
The bytes "0204" (which correspond to a temperature of 11.6 °C) are stored as `024` instead of `0204` in the "tempHex" variable, which decodes it to -36.4°C.
@MClimate - I encourage you guys to apply …
=> MClimate HT - Fix temperature decoding issue

vendor/plenom/busylight.js
The upcoming new devices will have a brighter LED.
To maintain compatibility to the current devices, they are shipped with low brightness configured.
We have added a flag to indicate if the device is running in low or high intensity mode
...
- removed debugging info from payload formatter
- added brightness flag to payload formatter
...
- ...
=> Added payload formatter for new high brightness devices

vendor/kamstrup/flowiq2200-02k73a.yaml, vendor/kamstrup/mbusparser.js, vendor/kamstrup/mbusparser.yaml
Add a generic codec for Kamstrup water meters based on standarized Mbus.
- Add codec (mbusparser.js) and codec test file (mbusparser.yaml).
- Updated .yaml for flowiq2200 meter to point to the added codc.
- New codec for Kamstrup water meters
=> Added codec and test script.

vendor/watteco/smartpilot-wire.yaml
There was a problem with encoding in one of the files which prevented the release.
- Fix encoding in `vendor/watteco/smartpilot-wire.yaml`
I don't think GH shows the difference between the lines
N/A
=> Fix Watteco SmartPilot Wire encoding

vendor/plenom/busylight.js
This PR contains the fix to this issue that has been raised - https://github.com/TheThingsNetwork/lorawan-devices/issues/910
This issue is that the Plenom Busylights payload formatter, has been displaying the following error when trying to decode the downlink message: `TypeError: Cannot read property '5' of undefined at decodeDownlink (<eval>:115:35(77))`
...
In the previous code the `s` in bytes was missing, as it was trying to do `input.byte[5]` instead of  `input.bytes[5]` 
I have updated the code to resolve this typo.
- [] Title and description should be descriptive (Not just a serial number for example).
- [] `profileIDs` should not be `vendorID` and should be a unique value for every profile.
- [] All devices should be listed in the vendor's `index.yaml` file.
- [] Firmware versions …
=> Fixing typo in plenom busy light formatter

website/webpack.config.js
Fixes [the following error](https://github.com/TheThingsNetwork/lorawan-devices/actions/runs/15824432900/job/44600958896). 
[Explanation](https://stackoverflow.com/a/73027407)
```
yarn run v1.22.22
$ webpack
node:internal/crypto/hash:79
this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:79:19)
at Object.createHash (node:crypto:139:10)
at module.exports (/home/runner/work/lorawan-devices/lorawan-devices/website/node_modules/webpack/lib/util/createHash.js:135:53)
at NormalModule._initBuildHash (/home/runner/work/lorawan-devices/lorawan-devices/website/node_modules/webpack/lib/NormalModule.js:417:16)
at handleParseError …
```
=> Set a hash function for Webpack
